# Generated by Django 4.1.7 on 2023-03-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_auth', '0003_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='isd',
            field=models.CharField(default=7, max_length=4, verbose_name='Телефонный код станы'),
        ),
    ]
